general:
  kafka-topic: kafka-topic
  kafka-group-id: kafka-group-id

server:
  port: 33400
  
spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      group-id: ${general.kafka-group-id}
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: milan
    password: test123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true





# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=yashi
# spring.datasource.password=test123
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# server.port=33400